repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
    name: Verify YAML syntax
    # args:
    # - --allow-multiple-documents

- repo: https://github.com/intelops/gitrepos-templates-policies
  rev: v0.0.1
  hooks:
  - id: check-gitsign
    name: Check gitsign
    description: Check if the last commit is signed with Sigstore gitsign
