repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  # Checks for files that contain merge conflict strings.
  - id: check-merge-conflict
  # Detects aws credentials from the aws cli credentials file.
  - id: detect-aws-credentials
  # detects the presence of private keys.
  - id: detect-private-key
  # Verifies that test files are named correctly.
  - id: name-tests-test
  # Trims trailing whitespace in codebase.
  - id: trailing-whitespace
    # Protect commit to main branch
  - id: no-commit-to-branch
    args: [--branch,main]

# Checks your git commit messages for style.
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
    name: Scan Commit messages

# Detects hardcoded secrets, security vulnerabilities and policy breaks using GGShield
# - repo: https://github.com/gitguardian/gg-shield
#   rev: v1.22.0
#   hooks:
#   - id: ggshield
#     name: Scan Secrets

# We can try out Gitleks as well: https://github.com/gitleaks/gitleaks
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.1
  hooks:
  - id: gitleaks
    name: Detect hardcoded secrets
    description: Detect hardcoded secrets using Gitleaks
    entry: gitleaks protect --verbose --redact --staged
    language: python
    pass_filenames: false


# Python specific Hooks
# Adds a trailing comma to calls and literals
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
    name: Add tailing comma

  # Reorders inports
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    name: Reorder imports

# Python code formatter
- repo: https://github.com/psf/black
  rev: v23.12.1
  hooks:
  - id: black
    name: Python code formatter

# Scan security issues in Python code.
- repo: https://github.com/PyCQA/bandit
  rev: v1.7.6
  hooks:
  - id: bandit
    name: Security scanner

# Static code analyser for Python
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.3
  hooks:
  - id: pylint
    name: Python linter





