# Terraform Hooks

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  name: Format terraform code
  id: terraform_fmt
  name: Validate Terraform code
  id: terraform_validate
  name: Static analysis of Terraform file
  id: terraform_tfsec
  name: Terraform scan with Trivytool
  id: terraform_trivy
  args:
     - >
       --args=--format json