# Terraform Hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
  - id: terraform_fmt
    name: Format terraform code
  - id: terraform_validate
    name: Validate Terraform code
  - id: terraform_tfsec
    name: Static analysis of Terraform file
  - id: terraform_trivy
    name: Terraform scan with Trivytool
    args:
       - >
         --args=--format json