# Dockerfile linter

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  name: DOckerfile linter
  id: hadolint
  # Rules you want to ignore may be found here: https://github.com/hadolint/hadolint?tab=readme-ov-file#rules
  args: [--ignore,DL3051]