repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
    name: Verify YAML syntax
    args:
    - --allow-multiple-documents

# - repo: https://github.com/adrienverge/yamllint
#   rev: v1.33.0
#   hooks:
#   - id: yamllint
#     name: A stricter YAML Linter
#     description: Checks syntax validity, line length, trainling whitespaces, indentation, etc.