repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0 
  hooks:
  # Checks for files that contain merge conflict strings.
  - id: check-merge-conflict
  # Detects aws credentials from the aws cli credentials file.
  - id: detect-aws-credentials
  # detects the presence of private keys.
  - id: detect-private-key
  # Verifies that test files are named correctly.
  - id: name-tests-test
  # Trims trailing whitespace in codebase.
  - id: trailing-whitespace

# Checks your git commit messages for style.
- repo: https://github.com/jorisroovers/gitlint
  name: Scan Commit messages
  rev: main
  - id: gitlint

# Detects hardcoded secrets, security vulnerabilities and policy breaks using GGShield
- repo: https://github.com/gitguardian/gg-shield
  name: Scan Secrets
  rev: v1.22.0
  hooks:
  - id: ggshield